function L2err = L2ProjectionErrorLinear(u1, p1, u2, p2)
    % calculate L2 norm of u1 - u2 where Pi is a projection onto
    % the space generated by linear basis functions on p2
    % p1 and p2 need to be on the same domain with the same
    % boundary points
    %
    % Inputs: 
    % u1: (N1,1) solution vector
    % u2: (N2,1) solution vector
    % p1: (N1,1) point vector of V1
    % p2: (N2,1) point vector of V2
    %
    % Outputs:
    % L2err: scalar L2 error

    % create span{V1,V2}
    p = sort([p1; p2]);
    p = unique(p);
    N = length(p);
    t = [(1:N-1)', (2:N)'];
    u1Interp = interp1(p1,u1,p);
    u2Interp = interp1(p2,u2,p);

    L2err = 0;
    for i = 1:size(t,1)
        h = abs(p(t(i,1))-p(t(i,2)));
        L2err = L2err + (h/2)*sum((u1Interp(t(i,:)) - u2Interp(t(i,:))).^2);
    end
    L2err = sqrt(L2err);
end